/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TasksNewRouteImport } from './routes/tasks/new'
import { Route as TasksIdRouteImport } from './routes/tasks/$id'
import { Route as TasksIdEditRouteImport } from './routes/tasks/$id.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksNewRoute = TasksNewRouteImport.update({
  id: '/tasks/new',
  path: '/tasks/new',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksIdRoute = TasksIdRouteImport.update({
  id: '/tasks/$id',
  path: '/tasks/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksIdEditRoute = TasksIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => TasksIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/tasks/$id': typeof TasksIdRouteWithChildren
  '/tasks/new': typeof TasksNewRoute
  '/tasks/$id/edit': typeof TasksIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/tasks/$id': typeof TasksIdRouteWithChildren
  '/tasks/new': typeof TasksNewRoute
  '/tasks/$id/edit': typeof TasksIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/tasks/$id': typeof TasksIdRouteWithChildren
  '/tasks/new': typeof TasksNewRoute
  '/tasks/$id/edit': typeof TasksIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/tasks/$id' | '/tasks/new' | '/tasks/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/tasks/$id' | '/tasks/new' | '/tasks/$id/edit'
  id: '__root__' | '/' | '/tasks/$id' | '/tasks/new' | '/tasks/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TasksIdRoute: typeof TasksIdRouteWithChildren
  TasksNewRoute: typeof TasksNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/new': {
      id: '/tasks/new'
      path: '/tasks/new'
      fullPath: '/tasks/new'
      preLoaderRoute: typeof TasksNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/$id': {
      id: '/tasks/$id'
      path: '/tasks/$id'
      fullPath: '/tasks/$id'
      preLoaderRoute: typeof TasksIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/$id/edit': {
      id: '/tasks/$id/edit'
      path: '/edit'
      fullPath: '/tasks/$id/edit'
      preLoaderRoute: typeof TasksIdEditRouteImport
      parentRoute: typeof TasksIdRoute
    }
  }
}

interface TasksIdRouteChildren {
  TasksIdEditRoute: typeof TasksIdEditRoute
}

const TasksIdRouteChildren: TasksIdRouteChildren = {
  TasksIdEditRoute: TasksIdEditRoute,
}

const TasksIdRouteWithChildren =
  TasksIdRoute._addFileChildren(TasksIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TasksIdRoute: TasksIdRouteWithChildren,
  TasksNewRoute: TasksNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
